Final changes
EhrlichNati/Garmin-Sports-Watch-Data-Cleanup pull request #3
Opened 2023-11-20 20:20 UTC by EhrlichNati

2023-11-22 08:12 UTC, erlichsefi requested changes

2023-11-22 08:12 UTC, erlichsefi commented on .idea/Garmin-Sports-Watch-Data-Cleanup.iml
can you add this `.idea` folder to `.gitignore`? I don't see why those configuration files need to be committed.

2023-11-22 08:12 UTC, erlichsefi commented on .idea/Garmin-Sports-Watch-Data-Cleanup.iml
i see you already pushed the `.idea ` folder, in order that git will detect it need to remove the folder from the remote, you need.
1. copy `.idea ` in your local to different location.
2. delete the `.idea ` in local project root.
3. now git will notice the deletion and you can `add`, `commit` and `push` them.
4. add `.idea ` to `.gitignore`
5. copy the folder back to the project root.

2023-11-28 10:07 UTC, merged

2023-11-29 08:41 UTC, erlichsefi commented
You didn't address my comments.

On Tue, 28 Nov 2023 at 12:08, EhrlichNati ***@***.***> wrote:

> Merged #3
> <https://github.com/EhrlichNati/Garmin-Sports-Watch-Data-Cleanup/pull/3>
> into main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EhrlichNati/Garmin-Sports-Watch-Data-Cleanup/pull/3#event-11081420082>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACIBTVUDDI4ZHCAJUSEPUXDYGWZX7AVCNFSM6AAAAAA7TPDOPWVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJRGA4DCNBSGAYDQMQ>
> .
> You are receiving this because you commented.Message ID:
> <EhrlichNati/Garmin-Sports-Watch-Data-Cleanup/pull/3/issue_event/11081420082
> @github.com>
>

2023-11-29 09:37 UTC, EhrlichNati commented
Fixed it now.
had some problem with the small details.

On Wed, 29 Nov 2023 at 10:41, Erlich Sefi ***@***.***> wrote:

> You didn't address my comments.
>
> On Tue, 28 Nov 2023 at 12:08, EhrlichNati ***@***.***> wrote:
>
> > Merged #3
> > <https://github.com/EhrlichNati/Garmin-Sports-Watch-Data-Cleanup/pull/3>
>
> > into main.
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/EhrlichNati/Garmin-Sports-Watch-Data-Cleanup/pull/3#event-11081420082>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/ACIBTVUDDI4ZHCAJUSEPUXDYGWZX7AVCNFSM6AAAAAA7TPDOPWVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJRGA4DCNBSGAYDQMQ>
>
> > .
> > You are receiving this because you commented.Message ID:
> >
> <EhrlichNati/Garmin-Sports-Watch-Data-Cleanup/pull/3/issue_event/11081420082
>
> > @github.com>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/EhrlichNati/Garmin-Sports-Watch-Data-Cleanup/pull/3#issuecomment-1831451761>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6UKTH7GUFWW3Z4G34DLRXLYG3YKTAVCNFSM6AAAAAA7TPDOPWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMZRGQ2TCNZWGE>
> .
> You are receiving this because you modified the open/close state.Message
> ID: <EhrlichNati/Garmin-Sports-Watch-Data-Cleanup/pull/3/c1831451761@
> github.com>
>